-- lua/mappings/treesitter.lua
-- ============================================================
-- ГОРЯЧИЕ КЛАВИШИ ДЛЯ TREESITTER
-- ============================================================
-- Все хоткеи для treesitter настроены в plugins/treesitter.lua
-- через opts.incremental_selection.keymaps и opts.textobjects.*.keymaps,
-- так как это специфичный API плагина.
-- Этот файл оставлен пустым для совместимости с core/init.lua.
